/* Curated charts + live radio stations.
   Songs are looked up against the free iTunes Search API at runtime to fetch
   album art and a 30-second preview clip. The lists below are the editorial
   "Top 50" — title + artist is enough to resolve a preview. */

const TOP_ENGLISH = [
  "Blinding Lights - The Weeknd",
  "Shape of You - Ed Sheeran",
  "Someone Like You - Adele",
  "Uptown Funk - Mark Ronson ft. Bruno Mars",
  "Rolling in the Deep - Adele",
  "Bad Guy - Billie Eilish",
  "Levitating - Dua Lipa",
  "Shake It Off - Taylor Swift",
  "Believer - Imagine Dragons",
  "Counting Stars - OneRepublic",
  "Perfect - Ed Sheeran",
  "Happy - Pharrell Williams",
  "Stay - The Kid LAROI & Justin Bieber",
  "As It Was - Harry Styles",
  "Anti-Hero - Taylor Swift",
  "Flowers - Miley Cyrus",
  "Sunflower - Post Malone & Swae Lee",
  "Watermelon Sugar - Harry Styles",
  "Don't Start Now - Dua Lipa",
  "Old Town Road - Lil Nas X",
  "Thinking Out Loud - Ed Sheeran",
  "Hello - Adele",
  "Royals - Lorde",
  "Radioactive - Imagine Dragons",
  "Get Lucky - Daft Punk ft. Pharrell Williams",
  "Take Me to Church - Hozier",
  "Cheap Thrills - Sia",
  "Closer - The Chainsmokers ft. Halsey",
  "Despacito - Luis Fonsi ft. Daddy Yankee",
  "Believe - Cher",
  "Roar - Katy Perry",
  "Rolling Stone - The Rolling Stones",
  "Viva La Vida - Coldplay",
  "Yellow - Coldplay",
  "Hey Jude - The Beatles",
  "Bohemian Rhapsody - Queen",
  "Smells Like Teen Spirit - Nirvana",
  "Sweet Child O' Mine - Guns N' Roses",
  "Hotel California - Eagles",
  "Wonderwall - Oasis",
  "Lose Yourself - Eminem",
  "Umbrella - Rihanna",
  "Firework - Katy Perry",
  "Hips Don't Lie - Shakira",
  "Sugar - Maroon 5",
  "Photograph - Ed Sheeran",
  "Heat Waves - Glass Animals",
  "Save Your Tears - The Weeknd",
  "drivers license - Olivia Rodrigo",
  "Unstoppable - Sia",
];

const TOP_MANDARIN = [
  "晴天 - 周杰倫",
  "稻香 - 周杰倫",
  "七里香 - 周杰倫",
  "告白氣球 - 周杰倫",
  "青花瓷 - 周杰倫",
  "夜曲 - 周杰倫",
  "簡單愛 - 周杰倫",
  "彩虹 - 周杰倫",
  "說好不哭 - 周杰倫",
  "演員 - 薛之謙",
  "丑八怪 - 薛之謙",
  "突然好想你 - 五月天",
  "倔強 - 五月天",
  "溫柔 - 五月天",
  "後來 - 劉若英",
  "月亮代表我的心 - 鄧麗君",
  "甜蜜蜜 - 鄧麗君",
  "童話 - 光良",
  "小幸運 - 田馥甄",
  "你就不要想起我 - 田馥甄",
  "修煉愛情 - 林俊傑",
  "江南 - 林俊傑",
  "她說 - 林俊傑",
  "醉赤壁 - 林俊傑",
  "可惜沒如果 - 林俊傑",
  "我懷念的 - 孫燕姿",
  "遇見 - 孫燕姿",
  "天黑黑 - 孫燕姿",
  "勇氣 - 梁靜茹",
  "寧夏 - 梁靜茹",
  "情歌 - 梁靜茹",
  "光年之外 - 鄧紫棋",
  "泡沫 - 鄧紫棋",
  "喜歡你 - 鄧紫棋",
  "演員 - 周深",
  "大魚 - 周深",
  "成都 - 趙雷",
  "南山南 - 馬頔",
  "董小姐 - 宋冬野",
  "理想三旬 - 陳鴻宇",
  "一萬次悲傷 - 逃跑計劃",
  "夜空中最亮的星 - 逃跑計劃",
  "好心分手 - 盧巧音",
  "K歌之王 - 陳奕迅",
  "十年 - 陳奕迅",
  "浮誇 - 陳奕迅",
  "富士山下 - 陳奕迅",
  "紅玫瑰 - 陳奕迅",
  "歲月神偷 - 金玟岐",
  "起風了 - 買辣椒也用券",
];

/* Public live internet radio. <audio> can stream these directly. */
const STATIONS = [
  { name: "Groove Salad", genre: "Ambient / Downtempo", emoji: "🌿", url: "https://ice1.somafm.com/groovesalad-128-mp3" },
  { name: "Indie Pop Rocks", genre: "Indie / Pop", emoji: "🎸", url: "https://ice1.somafm.com/indiepop-128-mp3" },
  { name: "Lush", genre: "Vocals / Chillout", emoji: "💫", url: "https://ice1.somafm.com/lush-128-mp3" },
  { name: "Beat Blender", genre: "Deep House", emoji: "🔊", url: "https://ice1.somafm.com/beatblender-128-mp3" },
  { name: "Secret Agent", genre: "Lounge / Spy Jazz", emoji: "🕵️", url: "https://ice1.somafm.com/secretagent-128-mp3" },
  { name: "Drone Zone", genre: "Atmospheric", emoji: "🌌", url: "https://ice1.somafm.com/dronezone-128-mp3" },
  { name: "Folk Forward", genre: "Indie Folk", emoji: "🍂", url: "https://ice1.somafm.com/folkfwd-128-mp3" },
  { name: "Boot Liquor", genre: "Americana / Country", emoji: "🥃", url: "https://ice1.somafm.com/bootliquor-128-mp3" },
  { name: "PopTron", genre: "Electro Pop", emoji: "✨", url: "https://ice1.somafm.com/poptron-128-mp3" },
  { name: "Seven Inch Soul", genre: "Vintage Soul", emoji: "🎤", url: "https://ice1.somafm.com/7soul-128-mp3" },
  { name: "Fluid", genre: "Future Soul / Hip-Hop", emoji: "💧", url: "https://ice1.somafm.com/fluid-128-mp3" },
  { name: "DEF CON Radio", genre: "Electronic", emoji: "🤖", url: "https://ice1.somafm.com/defcon-128-mp3" },
];
