/* Curated Top 50 hit lists + live radio.
   Each song: t = title, a = artist, y = YouTube video id ("" = open a YouTube
   search instead of embedding). Playback uses the embedded YouTube player;
   if an id is wrong/blocked the app auto-falls back to a YouTube search. */

const TOP_ENGLISH = [
  { t: "Blinding Lights", a: "The Weeknd", y: "4NRXx6U8ABQ" },
  { t: "Shape of You", a: "Ed Sheeran", y: "JGwWNGJdvx8" },
  { t: "Someone Like You", a: "Adele", y: "hLQl3WQQoQ0" },
  { t: "Uptown Funk", a: "Mark Ronson ft. Bruno Mars", y: "OPf0YbXqDm0" },
  { t: "Rolling in the Deep", a: "Adele", y: "rYEDA3JcQqw" },
  { t: "Bad Guy", a: "Billie Eilish", y: "DyDfgMOUjCI" },
  { t: "Levitating", a: "Dua Lipa", y: "TUVcZfQe-Kw" },
  { t: "Shake It Off", a: "Taylor Swift", y: "nfWlot6h_JM" },
  { t: "Believer", a: "Imagine Dragons", y: "7wtfhZwyrcc" },
  { t: "Counting Stars", a: "OneRepublic", y: "hT_nvWreIhg" },
  { t: "Perfect", a: "Ed Sheeran", y: "2Vv-BfVoq4g" },
  { t: "Happy", a: "Pharrell Williams", y: "ZbZSe6N_BXs" },
  { t: "STAY", a: "The Kid LAROI & Justin Bieber", y: "kTJczUoc26U" },
  { t: "As It Was", a: "Harry Styles", y: "H5v3kku4y6Q" },
  { t: "Anti-Hero", a: "Taylor Swift", y: "b1kbLwvqugk" },
  { t: "Flowers", a: "Miley Cyrus", y: "G7KNmW9a75Y" },
  { t: "Sunflower", a: "Post Malone & Swae Lee", y: "ApXoWvfEYVU" },
  { t: "Watermelon Sugar", a: "Harry Styles", y: "E07s5ZYygMg" },
  { t: "Don't Start Now", a: "Dua Lipa", y: "oygrmJFKYZY" },
  { t: "Old Town Road", a: "Lil Nas X ft. Billy Ray Cyrus", y: "r7qovpFAGrQ" },
  { t: "Thinking Out Loud", a: "Ed Sheeran", y: "lp-EO5I60KA" },
  { t: "Hello", a: "Adele", y: "YQHsXMglC9A" },
  { t: "Royals", a: "Lorde", y: "nlcIKh6sBtc" },
  { t: "Radioactive", a: "Imagine Dragons", y: "ktvTqknDobU" },
  { t: "Get Lucky", a: "Daft Punk ft. Pharrell Williams", y: "5NV6Rdv1a3I" },
  { t: "Take Me to Church", a: "Hozier", y: "MYSVMgRr6pw" },
  { t: "Cheap Thrills", a: "Sia", y: "nYh-n7EOtMA" },
  { t: "Closer", a: "The Chainsmokers ft. Halsey", y: "PT2_F-1esPk" },
  { t: "Despacito", a: "Luis Fonsi ft. Daddy Yankee", y: "kJQP7kiw5Fk" },
  { t: "Roar", a: "Katy Perry", y: "CevxZvSJLk8" },
  { t: "Viva La Vida", a: "Coldplay", y: "dvgZkm1xWPE" },
  { t: "Yellow", a: "Coldplay", y: "yKNxeF4KMsY" },
  { t: "Hey Jude", a: "The Beatles", y: "A_MjCqQoLLA" },
  { t: "Bohemian Rhapsody", a: "Queen", y: "fJ9rUzIMcZQ" },
  { t: "Smells Like Teen Spirit", a: "Nirvana", y: "hTWKbfoikeg" },
  { t: "Sweet Child O' Mine", a: "Guns N' Roses", y: "1w7OgIMMRc4" },
  { t: "Hotel California", a: "Eagles", y: "EqPtz5qN7HM" },
  { t: "Wonderwall", a: "Oasis", y: "bx1Bh8ZvH84" },
  { t: "Lose Yourself", a: "Eminem", y: "_Yhyp-_hX2s" },
  { t: "Umbrella", a: "Rihanna ft. Jay-Z", y: "CvBfHwUxHIk" },
  { t: "Firework", a: "Katy Perry", y: "QGJuMBdaqIw" },
  { t: "Hips Don't Lie", a: "Shakira", y: "DUT5rEU6pqM" },
  { t: "Sugar", a: "Maroon 5", y: "09R8_2nJtjg" },
  { t: "Photograph", a: "Ed Sheeran", y: "nSDgHBxUbVQ" },
  { t: "Heat Waves", a: "Glass Animals", y: "mRD0-GxqHVo" },
  { t: "Save Your Tears", a: "The Weeknd", y: "XXYlFuWEuKI" },
  { t: "drivers license", a: "Olivia Rodrigo", y: "ZmDBbnmKpqQ" },
  { t: "Señorita", a: "Shawn Mendes & Camila Cabello", y: "Pkh8UtuejGw" },
  { t: "Shallow", a: "Lady Gaga & Bradley Cooper", y: "bo_efYhYU2A" },
  { t: "Memories", a: "Maroon 5", y: "SlPhMPnQ58k" },
];

/* Mandarin top hits. Titles/artists are accurate; ids left blank tap straight
   through to the correct official video on YouTube. */
const TOP_MANDARIN = [
  { t: "告白氣球", a: "周杰倫 Jay Chou", y: "bu7nU9Mhpyo" },
  { t: "晴天", a: "周杰倫 Jay Chou", y: "" },
  { t: "稻香", a: "周杰倫 Jay Chou", y: "" },
  { t: "七里香", a: "周杰倫 Jay Chou", y: "" },
  { t: "青花瓷", a: "周杰倫 Jay Chou", y: "" },
  { t: "夜曲", a: "周杰倫 Jay Chou", y: "" },
  { t: "簡單愛", a: "周杰倫 Jay Chou", y: "" },
  { t: "說好不哭", a: "周杰倫 ft. 五月天阿信", y: "" },
  { t: "演員", a: "薛之謙", y: "" },
  { t: "丑八怪", a: "薛之謙", y: "" },
  { t: "突然好想你", a: "五月天 Mayday", y: "" },
  { t: "倔強", a: "五月天 Mayday", y: "" },
  { t: "溫柔", a: "五月天 Mayday", y: "" },
  { t: "後來", a: "劉若英", y: "" },
  { t: "月亮代表我的心", a: "鄧麗君 Teresa Teng", y: "" },
  { t: "甜蜜蜜", a: "鄧麗君 Teresa Teng", y: "" },
  { t: "童話", a: "光良 Michael Wong", y: "" },
  { t: "小幸運", a: "田馥甄 Hebe Tien", y: "" },
  { t: "魔鬼中的天使", a: "田馥甄 Hebe Tien", y: "" },
  { t: "修煉愛情", a: "林俊傑 JJ Lin", y: "" },
  { t: "江南", a: "林俊傑 JJ Lin", y: "" },
  { t: "她說", a: "林俊傑 JJ Lin", y: "" },
  { t: "可惜沒如果", a: "林俊傑 JJ Lin", y: "" },
  { t: "醉赤壁", a: "林俊傑 JJ Lin", y: "" },
  { t: "我懷念的", a: "孫燕姿 Stefanie Sun", y: "" },
  { t: "遇見", a: "孫燕姿 Stefanie Sun", y: "" },
  { t: "天黑黑", a: "孫燕姿 Stefanie Sun", y: "" },
  { t: "勇氣", a: "梁靜茹 Fish Leong", y: "" },
  { t: "寧夏", a: "梁靜茹 Fish Leong", y: "" },
  { t: "情歌", a: "梁靜茹 Fish Leong", y: "" },
  { t: "光年之外", a: "鄧紫棋 G.E.M.", y: "" },
  { t: "泡沫", a: "鄧紫棋 G.E.M.", y: "" },
  { t: "喜歡你", a: "鄧紫棋 G.E.M.", y: "" },
  { t: "大魚", a: "周深 Zhou Shen", y: "" },
  { t: "成都", a: "趙雷", y: "" },
  { t: "南山南", a: "馬頔", y: "" },
  { t: "董小姐", a: "宋冬野", y: "" },
  { t: "理想三旬", a: "陳鴻宇", y: "" },
  { t: "夜空中最亮的星", a: "逃跑計劃", y: "" },
  { t: "K歌之王", a: "陳奕迅 Eason Chan", y: "" },
  { t: "十年", a: "陳奕迅 Eason Chan", y: "" },
  { t: "浮誇", a: "陳奕迅 Eason Chan", y: "" },
  { t: "富士山下", a: "陳奕迅 Eason Chan", y: "" },
  { t: "紅玫瑰", a: "陳奕迅 Eason Chan", y: "" },
  { t: "好心分手", a: "盧巧音 / 王力宏", y: "" },
  { t: "起風了", a: "買辣椒也用券", y: "" },
  { t: "起風了 (吳青峰)", a: "吳青峰", y: "" },
  { t: "年少有為", a: "李榮浩", y: "" },
  { t: "模特", a: "李榮浩", y: "" },
  { t: "知足", a: "五月天 Mayday", y: "" },
];

/* Public live internet radio. <audio> can stream these directly.
   SomaFM streams are rock-solid; the Mandarin/Asian community streams are
   public but may occasionally rotate URLs — swap them here if one is down. */
const STATIONS = [
  // --- Chill & Eclectic (SomaFM) ---
  { name: "Groove Salad", genre: "Ambient / Downtempo", emoji: "🌿", group: "Chill & Eclectic", url: "https://ice1.somafm.com/groovesalad-128-mp3" },
  { name: "Indie Pop Rocks", genre: "Indie / Pop", emoji: "🎸", group: "Chill & Eclectic", url: "https://ice1.somafm.com/indiepop-128-mp3" },
  { name: "Lush", genre: "Vocals / Chillout", emoji: "💫", group: "Chill & Eclectic", url: "https://ice1.somafm.com/lush-128-mp3" },
  { name: "Beat Blender", genre: "Deep House", emoji: "🔊", group: "Chill & Eclectic", url: "https://ice1.somafm.com/beatblender-128-mp3" },
  { name: "Secret Agent", genre: "Lounge / Spy Jazz", emoji: "🕵️", group: "Chill & Eclectic", url: "https://ice1.somafm.com/secretagent-128-mp3" },
  { name: "Drone Zone", genre: "Atmospheric", emoji: "🌌", group: "Chill & Eclectic", url: "https://ice1.somafm.com/dronezone-128-mp3" },
  { name: "Folk Forward", genre: "Indie Folk", emoji: "🍂", group: "Chill & Eclectic", url: "https://ice1.somafm.com/folkfwd-128-mp3" },
  { name: "Boot Liquor", genre: "Americana / Country", emoji: "🥃", group: "Chill & Eclectic", url: "https://ice1.somafm.com/bootliquor-128-mp3" },
  { name: "PopTron", genre: "Electro Pop", emoji: "✨", group: "Chill & Eclectic", url: "https://ice1.somafm.com/poptron-128-mp3" },
  { name: "Seven Inch Soul", genre: "Vintage Soul", emoji: "🎤", group: "Chill & Eclectic", url: "https://ice1.somafm.com/7soul-128-mp3" },
  { name: "Fluid", genre: "Future Soul / Hip-Hop", emoji: "💧", group: "Chill & Eclectic", url: "https://ice1.somafm.com/fluid-128-mp3" },
  { name: "DEF CON Radio", genre: "Electronic", emoji: "🤖", group: "Chill & Eclectic", url: "https://ice1.somafm.com/defcon-128-mp3" },

  // --- Mandarin & Asian Pop (community public streams) ---
  { name: "Hit FM 聯播網", genre: "Taiwan Mandarin Pop", emoji: "🇹🇼", group: "Mandarin & Asian", url: "https://stream.rcs.revma.com/em90w4aqwxquv" },
  { name: "KISS Radio 大眾廣播", genre: "Mandarin Hits", emoji: "💋", group: "Mandarin & Asian", url: "https://onair5.rcs.com.tw/991_live.mp3" },
  { name: "RTHK Radio 2", genre: "Cantonese / HK Pop", emoji: "🇭🇰", group: "Mandarin & Asian", url: "https://rthkaudio2-live.akamaized.net/hls/live/2040078/radio2/master.m3u8" },
  { name: "Asia DREAM Radio – C-Pop", genre: "Chinese Pop Mix", emoji: "🏮", group: "Mandarin & Asian", url: "https://kathy.torontocast.com:3060/;" },
];
